//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PupilIsNotStudent.automated_testing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RawTextExamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RawTextExamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PupilIsNotStudent.automated_testing.RawTextExamples", typeof(RawTextExamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to США і Китай домовилися про перемир&apos;я в торговельній війні 10:58, 15 грудня 2019 ФІНАНСИ 633 0 Конкретні умови перемир&apos;я відомі лише зі слів американської сторони. США та Китай домовилися про торговельну угоду / Ілюстрація REUTERS Вашингтон і Пекін домовилися призупинити торгову війну, яка завдала світовій економіці збитку на сотні мільярдів доларів. Читайте також 123 твіти за добу: Трамп встановив особистий рекорд в Twitter Як повідомляє «Русская служба BBC», угоду оголошено, але не підписано - сторони мают [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string longTextEconomy {
            get {
                return ResourceManager.GetString("longTextEconomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОЛОВНІ ПРИЧИНИ ЗВЕРНЕННЯ ДО СІМЕЙНОГО ЛІКАРЯ В УКРАЇНІ – ГОСТРІ СИМПТОМИ ХВОРОБИ НОВОСТИ МЕДИЦИНЫ 144 20 ИЮНЯ 2020 14:57 ОЛЬГА КУПРИЯНОВА ГОЛОВНІ ПРИЧИНИ ЗВЕРНЕННЯ ДО СІМЕЙНОГО ЛІКАРЯ В УКРАЇНІ – ГОСТРІ СИМПТОМИ ХВОРОБИ Фахівці проекту USAID Україна «Підтримка реформи охорони здоров’я» провели дослідження на тему «Оцінка поведінки провайдерів первинної медичної допомоги». В цьому дослідженні вони проаналізували зміни, які відбулися у наданні медичної допомоги сімейними лікарями, педіатрами та терапевтами з [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string longTextHealth {
            get {
                return ResourceManager.GetString("longTextHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подорожі в ЄС: в Кабміні розповіли, що буде з безвізом для українців
        ///Безвізовий режим України з країнами Євросоюзу продовжить діяти, незважаючи на обмеження через пандемію коронавірусу. Про це розповіла віце-прем’єр з євроінтеграції Ольга Стефанишин.
        ///
        ///“Він є, був і продовжує бути. Так, є певні обмеження, але вони пов’язані із заходами попередження пандемії, а не з наявністю або відсутністю безвізу. Це тимчасові обмеження, які діють не тільки щодо України, а щодо тих країн, з якими у ЄС є як безвізовий, т [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string longTextPolitics {
            get {
                return ResourceManager.GetString("longTextPolitics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдревніший у світі печерний малюнок містить елементи ранньої міфології Вчені кажуть, що це змінює уявлення науки про фантазію й вірування найдревніших представників нашого виду Малюнку, знайденому в Індонезії, 44 тисячі років / Griffith University Печерні малюнки зображують фігурки, в яких поєднуються риси людей і тварин. Вони полюють на бородавчатих свиней і карликових бичків. Цим малюнкам приблизно 44 тисяч років. Таким чином, це найдревніший з відомих зразків печерного мистецтва, створений представника [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string longTextScience {
            get {
                return ResourceManager.GetString("longTextScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Більшість популярних менеджерів паролів функціонують як хмарні додатки, до яких можна отримати доступ через браузер. Фахівці міжнародного розробника антивірусного програмного забезпечення, експерта в галузі кіберзахисту – компанії ESET розповіли, як правильно вибрати менеджер паролів – додаток, який спеціально розроблено для зберігання реєстраційних даних в зашифрованому сховищі, а також для створення складних комбінацій, що дозволяє надійно захистити облікові записи. Про це повідомила прес-служба компанії  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string longTextScience1 {
            get {
                return ResourceManager.GetString("longTextScience1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лідер &quot;Динамо&quot; звернувся до фанів клубу перед матчем ЛЄ
        ///15 лютого 2019, 10:201.9тЧитати матеріал російською
        ///Один із героїв першого матчу 1/16 фіналу Ліги Європи проти грецького &quot;Олімпіакоса&quot; півзахисник &quot;Динамо&quot; Беньямін Вербич дав після гри коментар місцевим журналістам.
        ///
        ///Беньямін ВербичПоділитися
        ///зображенням    
        ///Беньямін Вербич
        ///
        ///&quot;Важливо, що в результаті нам вдалося забити. Ми провели відмінний другий тайм. У першій половині діяли не дуже добре і дозволили &quot;Олімпіакосу&quot; забити два м&apos;ячі.
        ///
        ///Мені с [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string longTextSport {
            get {
                return ResourceManager.GetString("longTextSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Україна відновлює регулярні авіарейси: куди можна полетіти
        ///Новини » Суспільство     19.06.2020 - 18:02Новость на русском
        ///Україна відновлює регулярні авіарейси: куди можна полетіти
        ///Фото: Україна зняла обмеження на авіаперевезення (РБК-Україна)
        ///Авіакомпанії поступово збільшують число доступних напрямків
        ///
        ///Україна виходить з карантину і відновлює авіаперельоти. На цей час про плани знову почати літати до українських аеропортів заявили понад 15 авіакомпаній. При цьому міжнародні рейси вводяться в розклад п [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string longTextTourism {
            get {
                return ResourceManager.GetString("longTextTourism", resourceCulture);
            }
        }
    }
}
