//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Text_analyzer.automated_testing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RawTextExamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RawTextExamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Text_analyzer.automated_testing.RawTextExamples", typeof(RawTextExamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лідер &quot;Динамо&quot; звернувся до фанів клубу перед матчем ЛЄ
        ///15 лютого 2019, 10:201.9тЧитати матеріал російською
        ///Один із героїв першого матчу 1/16 фіналу Ліги Європи проти грецького &quot;Олімпіакоса&quot; півзахисник &quot;Динамо&quot; Беньямін Вербич дав після гри коментар місцевим журналістам.
        ///
        ///Беньямін ВербичПоділитися
        ///зображенням    
        ///Беньямін Вербич
        ///
        ///&quot;Важливо, що в результаті нам вдалося забити. Ми провели відмінний другий тайм. У першій половині діяли не дуже добре і дозволили &quot;Олімпіакосу&quot; забити два м&apos;ячі.
        ///
        ///Мені с [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string longTextSport {
            get {
                return ResourceManager.GetString("longTextSport", resourceCulture);
            }
        }
    }
}
